# Generated by Django 3.2.10 on 2022-09-30 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_propiedad', models.CharField(max_length=250, null=True)),
                ('tipo_propiedad', models.CharField(max_length=250, null=True)),
                ('ubicacion', models.CharField(max_length=250, null=True)),
                ('metros_cuadrados', models.CharField(max_length=250, null=True)),
                ('renta_o_venta', models.CharField(max_length=250, null=True)),
                ('precio', models.CharField(max_length=300, null=True)),
                ('n_habitaciones', models.CharField(max_length=250, null=True)),
                ('estado_habitaciones', models.CharField(max_length=250, null=True)),
                ('disponible', models.BooleanField(default=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
