# Generated by Django 3.2.10 on 2022-10-18 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instalacionapp', '0002_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('apellido', models.CharField(max_length=250, null=True)),
                ('correo', models.CharField(max_length=250, null=True)),
                ('numero', models.CharField(max_length=250, null=True)),
                ('pago', models.BooleanField(default=False, null=True)),
                ('total', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tienda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
