# Generated by Django 4.2.4 on 2023-09-20 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instalacionapp', '0004_marca_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='numero',
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instalacionapp.producto')),
                ('total', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instalacionapp.tienda')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
