# Generated by Django 4.2.4 on 2023-09-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalacionapp', '0005_remove_tienda_apellido_remove_tienda_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='pago',
        ),
    ]
