# Generated by Django 4.2.4 on 2023-09-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalacionapp', '0009_remove_producto_usuario_producto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='pago',
        ),
    ]
