# Generated by Django 4.2.4 on 2023-09-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacionapp', '0010_remove_producto_descripcion_remove_tienda_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='total',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='total',
        ),
        migrations.AddField(
            model_name='producto',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
