# Generated by Django 4.2.4 on 2023-09-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacionapp', '0011_remove_detalle_total_remove_tienda_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='total',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='user',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
