# Generated by Django 4.2.4 on 2023-09-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instalacionapp', '0013_historialcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='total',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='instalacionapp.tienda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tienda',
            name='pago',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistorialCompra',
        ),
    ]
