# Generated by Django 4.2.4 on 2023-09-26 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instalacionapp', '0017_tienda_nombre_alter_detalle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='detalle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to=settings.AUTH_USER_MODEL),
        ),
    ]
